package com.compose.androidexpertc1.presentation.theme

import androidx.compose.ui.graphics.Color

val themeLightPrimary = Color(0xFF825500)
val themeLightOnPrimary = Color(0xFFFFFFFF)
val themeLightPrimaryContainer = Color(0xFFFFDDAE)
val themeLightOnPrimaryContainer = Color(0xFF2A1800)
val themeLightSecondary = Color(0xFF6F5B40)
val themeLightOnSecondary = Color(0xFFFFFFFF)
val themeLightSecondaryContainer = Color(0xFFFADEBC)
val themeLightOnSecondaryContainer = Color(0xFF271904)
val themeLightTertiary = Color(0xFF516440)
val themeLightOnTertiary = Color(0xFFFFFFFF)
val themeLightTertiaryContainer = Color(0xFFD3EABC)
val themeLightOnTertiaryContainer = Color(0xFF102004)
val themeLightError = Color(0xFFBA1B1B)
val themeLightErrorContainer = Color(0xFFFFDAD4)
val themeLightOnError = Color(0xFFFFFFFF)
val themeLightOnErrorContainer = Color(0xFF410001)
val themeLightBackground = Color(0xFFFCFCFC)
val themeLightOnBackground = Color(0xFF1F1B16)
val themeLightSurface = Color(0xFFFCFCFC)
val themeLightOnSurface = Color(0xFF1F1B16)
val themeLightSurfaceVariant = Color(0xFFF0E0CF)
val themeLightOnSurfaceVariant = Color(0xFF4F4539)
val themeLightOutline = Color(0xFF817567)
val themeLightInverseOnSurface = Color(0xFFF9EFE6)
val themeLightInverseSurface = Color(0xFF34302A)
val themeLightPrimaryInverse = Color(0xFFFFB945)

val themeDarkPrimary = Color(0xFFFFB945)
val themeDarkOnPrimary = Color(0xFF452B00)
val themeDarkPrimaryContainer = Color(0xFF624000)
val themeDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val themeDarkSecondary = Color(0xFFDDC3A2)
val themeDarkOnSecondary = Color(0xFF3E2E16)
val themeDarkSecondaryContainer = Color(0xFF56442B)
val themeDarkOnSecondaryContainer = Color(0xFFFADEBC)
val themeDarkTertiary = Color(0xFFB8CEA2)
val themeDarkOnTertiary = Color(0xFF243516)
val themeDarkTertiaryContainer = Color(0xFF3A4C2B)
val themeDarkOnTertiaryContainer = Color(0xFFD3EABC)
val themeDarkError = Color(0xFFFFB4A9)
val themeDarkErrorContainer = Color(0xFF930006)
val themeDarkOnError = Color(0xFF680003)
val themeDarkOnErrorContainer = Color(0xFFFFDAD4)
val themeDarkBackground = Color(0xFF1F1B16)
val themeDarkOnBackground = Color(0xFFEAE1D9)
val themeDarkSurface = Color(0xFF1F1B16)
val themeDarkOnSurface = Color(0xFFEAE1D9)
val themeDarkSurfaceVariant = Color(0xFF4F4539)
val themeDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val themeDarkOutline = Color(0xFF9C8F80)
val themeDarkInverseOnSurface = Color(0xFF32281A)
val themeDarkInverseSurface = Color(0xFFEAE1D9)
val themeDarkPrimaryInverse = Color(0xFF624000)